export class Translator {

    options: string[] = [
        'Afghanistan',
        'Algeria',
        'Albania',
        'Angola',
        'Argentina',
        'Armenia',
        'Australia',
        'Austria',
        'Azerbaijan',
        'Bahrain',
        'Bangladesh',
        'Barbados',
        'Belarus',
        'Belize',
        'Belgium',
        'Bosnia and Herzegovina',
        'Brazil',
        'Bhutan',
        'Bulgaria',
        'Cambodia',
        'Canada',
        'China',
        'Costa Rica',
        'Croatia',
        'Cuba',
        'Czech Republic',
        'Denmark',
        'Dominica',
        'Egypt',
        'El Salvador',
        'Estonia',
        'Ethiopia',
        'Finland',
        'Fiji',
        'France',
        'Georgia',
        'Germany',
        'Ghana',
        'Grenada',
        'Guatemala',
        'Hong Kong',
        'Hungary',
        'Iceland',
        'India',
        'Indonesia',
        'Iran',
        'Iraq',
        'Israel',
        'Italy',
        'Jamaica',
        'Japan',
        'Jordan',
        'Kazakhstan',
        'Kenya',
        'Kiribati',
        'Kosovo',
        'Kuwait',
        'Kyrgyzstan',
        'Laos',
        'Latvia',
        'Lebanon',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Macedonia',
        'Malaysia',
        'Maldives',
        'Mexico',
        'Moldova',
        'Monaco',
        'Mongolia',
        'Morocco',
        'Myanmar',
        'Namibia',
        'Nepal',
        'Netherlands',
        'New Zealand',
        'Nicaragua',
        'Nigeria',
        'North Korea',
        'Norway',
        'Oman',
        'Pakistan',
        'Palau',
        'Panama',
        'Papua New Guinea',
        'Philippines',
        'Poland',
        'Portugal',
        'Qatar',
        'Romania',
        'Russia',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Vincent and the Grenadines',
        'Senegal',
        'Serbia',
        'Singapore',
        'Slovakia',
        'Slovenia',
        'South Africa',
        'South Korea',
        'Spain',
        'Sri Lanka',
        'Sudan',
        'Sweden',
        'Switzerland',
        'Syria',
        'Taiwan',
        'Tajikistan',
        'Tanzania',
        'Thailand',
        'The Gambia',
        'Trinidad and Tobago',
        'Turkey',
        'Turkmenistan',
        'Uganda',
        'United Arab Emirates',
        'United Kingdom',
        'United States',
        'Uzbekistan',
        'Vanuatu',
        'Vietnam',
        'Zimbabwe',
        'አፍጋኒስታን',
        'አልጀሪያ',
        'አልባኒያ',
        'አንጎላ',
        'አርጀንቲና',
        'አርሜኒያ',
        'አውስትሬሊያ',
        'ኦስትሪያ',
        'አዘርባይጃን',
        'ባህሬን',
        'ባንግላዲሽ',
        'ባርቤዶስ',
        'ቤላሩስ',
        'ቤሊዝ',
        'ቤልጄም',
        'ቦስኒያ እና ሄርዘጎቪኒያ',
        'ብራዚል',
        'ቡታን',
        'ቡልጋሪያ',
        'ካምቦዲያ',
        'ካናዳ',
        'ቻይና',
        'ኮስታ ሪካ',
        'ክሮኤሽያ',
        'ኩባ',
        'ቼክ ሪፑብሊክ',
        'ዴንማርክ',
        'ዶሚኒካ',
        'ግብፅ',
        'ኤል ሳልቫዶር',
        'ኤስቶኒያ',
        'ኢትዮጵያ',
        'ፊንላንድ',
        'ፊጂ',
        'ፈረንሳይ',
        'ጊዮርጂያ',
        'ጀርመን',
        'ጋና',
        'ግሬናዳ',
        'ጉዋቲማላ',
        'ሆንግ ኮንግ',
        'ሁንጋሪ',
        'አይስላንድ',
        'ህንድ',
        'ኢንዶኔዢያ',
        'ኢራን',
        'ኢራቅ',
        'እስራኤል',
        'ኢጣሊያ',
        'ጃማይካ',
        'ጃፓን',
        'ጆርዳን',
        'ካዛኪስታን',
        'ኬንያ',
        'ኪሪባቲ',
        'ኮሶቮ',
        'ኩዌት',
        'ኪርጊስታን',
        'ላኦስ',
        'ላትቪያ',
        'ሊባኖስ',
        'ሊክተንስታይን',
        'ሊቱዌኒያ',
        'ሉክሰምበርግ',
        'ማኬዶንያ',
        'ማሌዥያ',
        'ማልዲቭስ',
        'ሜክሲኮ',
        'ሞልዶቫ',
        'ሞናኮ',
        'ሞንጎሊያ',
        'ሞሮኮ',
        'ማይናማር (በርማ)',
        'ናሚቢያ',
        'ኔፓል',
        'ኔዘርላንድ',
        'ኒው ዚላንድ',
        'ኒካራጓ',
        'ናይጄሪያ',
        'ሰሜን ኮሪያ',
        'ኖርዌ',
        'ኦማን',
        'ፓኪስታን',
        'ፓላው',
        'ፓናማ',
        'ፓፑዋ ኒው ጊኒ',
        'ፊሊፒንስ',
        'ፖላንድ',
        'ፖርቱጋል',
        'ኳታር',
        'ሮሜኒያ',
        'ሩሲያ',
        'ሴንት ኪትስ እና ኔቪስ',
        'ሴንት ሉሺያ',
        'ሴንት ቪንሴንት እና ግሬናዲንስ',
        'ሴኔጋል',
        'ሰርቢያ',
        'ሲንጋፖር',
        'ስሎቫኪያ',
        'ስሎቬኒያ',
        'ደቡብ አፍሪካ',
        'ደቡብ ኮሪያ',
        'ስፔን',
        'ስሪ ላንካ',
        'ሱዳን',
        'ስዊድን',
        'ስዊዘርላንድ',
        'ሲሪያ',
        'ታይዋን',
        'ታጂኪስታን',
        'ታንዛኒያ',
        'ታይላንድ',
        'ጋምቢያ',
        'ትሪኒዳድ እና ቶባጎ',
        'ቱርኪ',
        'ቱርክሜኒስታን',
        'ዩጋንዳ',
        'የአረብ ኤምሬት',
        'እንግሊዝ',
        'አሜሪካ',
        'ዩናትድ እስቴት',
        'ኡዝበኪስታን',
        'ቫኑአቱ',
        'ቬትናም',
        'ዚምቧቄ'
    ];

    countryMap: { [key: string]: string } = {
        "አፍጋኒስታን": "Afghanistan",
        "አልጀሪያ": "Algeria",
        "አልባኒያ": "Albania",
        "አንጎላ": "Angola",
        "አርጀንቲና": "Argentina",
        "አርሜኒያ": "Armenia",
        "አውስትሬሊያ": "Australia",
        "ኦስትሪያ": "Austria",
        "አዘርባይጃን": "Azerbaijan",
        "ባህሬን": "Bahrain",
        "ባንግላዲሽ": "Bangladesh",
        "ባርቤዶስ": "Barbados",
        "ቤላሩስ": "Belarus",
        "ቤሊዝ": "Belize",
        "ቤልጄም": "Belgium",
        "ቦስኒያ እና ሄርዘጎቪኒያ": "Bosnia and Herzegovina",
        "ብራዚል": "Brazil",
        "ቡታን": "Bhutan",
        "ቡልጋሪያ": "Bulgaria",
        "ካምቦዲያ": "Cambodia",
        "ካናዳ": "Canada",
        "ቻይና": "China",
        "ኮስታ ሪካ": "Costa Rica",
        "ክሮኤሽያ": "Croatia",
        "ኩባ": "Cuba",
        "ቼክ ሪፑብሊክ": "Czech Republic",
        "ዴንማርክ": "Denmark",
        "ዶሚኒካ": "Dominica",
        "ግብፅ": "Egypt",
        "ኤል ሳልቫዶር": "El Salvador",
        "ኤስቶኒያ": "Estonia",
        "ኢትዮጵያ": "Ethiopia",
        "ፊንላንድ": "Finland",
        "ፊጂ": "Fiji",
        "ፈረንሳይ": "France",
        "ጊዮርጂያ": "Georgia",
        "ጀርመን": "Germany",
        "ጋና": "Ghana",
        "ግሬናዳ": "Grenada",
        "ጉዋቲማላ": "Guatemala",
        "ሆንግ ኮንግ": "Hong Kong",
        "ሁንጋሪ": "Hungary",
        "አይስላንድ": "Iceland",
        "ህንድ": "India",
        "ኢንዶኔዢያ": "Indonesia",
        "ኢራን": "Iran",
        "ኢራቅ": "Iraq",
        "እስራኤል": "Israel",
        "ኢጣሊያ": "Italy",
        "ጃማይካ": "Jamaica",
        "ጃፓን": "Japan",
        "ጆርዳን": "Jordan",
        "ካዛኪስታን": "Kazakhstan",
        "ኬንያ": "Kenya",
        "ኪሪባቲ": "Kiribati",
        "ኮሶቮ": "Kosovo",
        "ኩዌት": "Kuwait",
        "ኪርጊስታን": "Kyrgyzstan",
        "ላኦስ": "Laos",
        "ላትቪያ": "Latvia",
        "ሊባኖስ": "Lebanon",
        "ሊክተንስታይን": "Liechtenstein",
        "ሊቱዌኒያ": "Lithuania",
        "ሉክሰምበርግ": "Luxembourg",
        "ማኬዶንያ": "Macedonia",
        "ማሌዥያ": "Malaysia",
        "ማልዲቭስ": "Maldives",
        "ሜክሲኮ": "Mexico",
        "ሞልዶቫ": "Moldova",
        "ሞናኮ": "Monaco",
        "ሞንጎሊያ": "Mongolia",
        "ሞሮኮ": "Morocco",
        "ማይናማር (በርማ)": "Myanmar (Burma)",
        "ናሚቢያ": "Namibia",
        "ኔፓል": "Nepal",
        "ኔዘርላንድ": "Netherlands",
        "ኒው ዚላንድ": "New Zealand",
        "ኒካራጓ": "Nicaragua",
        "ናይጄሪያ": "Nigeria",
        "ሰሜን ኮሪያ": "North Korea",
        "ኖርዌ": "Norway",
        "ኦማን": "Oman",
        "ፓኪስታን": "Pakistan",
        "ፓላው": "Palau",
        "ፓናማ": "Panama",
        "ፓፑዋ ኒው ጊኒ": "Papua New Guinea",
        "ፊሊፒንስ": "Philippines",
        "ፖላንድ": "Poland",
        "ፖርቱጋል": "Portugal",
        "ኳታር": "Qatar",
        "ሮሜኒያ": "Romania",
        "ሩሲያ": "Russia",
        "ሴንት ኪትስ እና ኔቪስ": "Saint Kitts and Nevis",
        "ሴንት ሉሺያ": "Saint Lucia",
        "ሴንት ቪንሴንት እና ግሬናዲንስ": "Saint Vincent and the Grenadines",
        "ሴኔጋል": "Senegal",
        "ሰርቢያ": "Serbia",
        "ሲንጋፖር": "Singapore",
        "ስሎቫኪያ": "Slovakia",
        "ስሎቬኒያ": "Slovenia",
        "ደቡብ አፍሪካ": "South Africa",
        "ደቡብ ኮሪያ": "South Korea",
        "ስፔን": "Spain",
        "ስሪ ላንካ": "Sri Lanka",
        "ሱዳን": "Sudan",
        "ስዊድን": "Sweden",
        "ስዊዘርላንድ": "Switzerland",
        "ሲሪያ": "Syria",
        "ታይዋን": "Taiwan",
        "ታጂኪስታን": "Tajikistan",
        "ታንዛኒያ": "Tanzania",
        "ታይላንድ": "Thailand",
        "ጋምቢያ": "The Gambia",
        "ትሪኒዳድ እና ቶባጎ": "Trinidad and Tobago",
        "ቱርኪ": "Turkey",
        "ቱርክሜኒስታን": "Turkmenistan",
        "ዩጋንዳ": "Uganda",
        "የአረብ ኤምሬት": "United Arab Emirates",
        "እንግሊዝ": "United Kingdom",
        "አሜሪካ": "United States",
        "ዩናትድ እስቴት": "United States",
        "ኡዝበኪስታን": "Uzbekistan",
        "ቫኑአቱ": "Vanuatu",
        "ቬትናም": "Vietnam",
        "ዚምቧቄ": "Zimbabwe"
    };

    private amharicToEnglish: { [key: string]: string } = {
        "ሀ": "he",
        "ሁ": "hu",
        "ሂ": "hi",
        "ሃ": "ha",
        "ሄ": "hee",
        "ህ": "h",
        "ሆ": "ho",
        "ለ": "le",
        "ሉ": "lu",
        "ሊ": "li",
        "ላ": "la",
        "ሌ": "lee",
        "ል": "l",
        "ሎ": "lo",
        "ሏ": "laa",
        "ሐ": "He",
        "ሑ": "Hu",
        "ሒ": "Hi",
        "ሓ": "Ha",
        "ሔ": "Hee",
        "ሕ": "H",
        "ሖ": "Ho",
        "ሗ": "Haa",
        "መ": "me",
        "ሙ": "mu",
        "ሚ": "mi",
        "ማ": "ma",
        "ሜ": "mee",
        "ም": "m",
        "ሞ": "mo",
        "ሟ": "maa",
        "ሠ": "sze",
        "ሡ": "szu",
        "ሢ": "szi",
        "ሣ": "sza",
        "ሤ": "szee",
        "ሥ": "sz",
        "ሦ": "szo",
        "ሧ": "szaa",
        "ረ": "re",
        "ሩ": "ru",
        "ሪ": "ri",
        "ራ": "ra",
        "ሬ": "ree",
        "ር": "r",
        "ሮ": "ro",
        "ሯ": "raa",
        "ሰ": "se",
        "ሱ": "su",
        "ሲ": "si",
        "ሳ": "sa",
        "ሴ": "see",
        "ስ": "s",
        "ሶ": "so",
        "ሷ": "saa",
        "ሸ": "she",
        "ሹ": "shu",
        "ሺ": "shi",
        "ሻ": "sha",
        "ሼ": "shee",
        "ሽ": "sh",
        "ሾ": "sho",
        "ሿ": "shaa",
        "ቀ": "qe",
        "ቁ": "qu",
        "ቂ": "qi",
        "ቃ": "qa",
        "ቄ": "qee",
        "ቅ": "q",
        "ቆ": "qo",
        "ቇ": "qaa",
        "በ": "be",
        "ቡ": "bu",
        "ቢ": "bi",
        "ባ": "ba",
        "ቤ": "bee",
        "ብ": "b",
        "ቦ": "bo",
        "ቧ": "baa",
        "ቨ": "ve",
        "ቩ": "vu",
        "ቪ": "vi",
        "ቫ": "va",
        "ቬ": "vee",
        "ቭ": "v",
        "ቮ": "vo",
        "ቯ": "vaa",
        "ተ": "te",
        "ቱ": "tu",
        "ቲ": "ti",
        "ታ": "ta",
        "ቴ": "tee",
        "ት": "t",
        "ቶ": "to",
        "ቷ": "taa",
        "ቸ": "ce",
        "ቹ": "cu",
        "ቺ": "ci",
        "ቻ": "ca",
        "ቼ": "cee",
        "ች": "c",
        "ቾ": "co",
        "ቿ": "caa",
        "ኀ": "Xe",
        "ኁ": "Xu",
        "ኂ": "Xi",
        "ኃ": "Xa",
        "ኄ": "Xee",
        "ኅ": "X",
        "ኆ": "Xo",
        "ኇ": "Xaa",
        "ነ": "ne",
        "ኑ": "nu",
        "ኒ": "ni",
        "ና": "na",
        "ኔ": "nee",
        "ን": "n",
        "ኖ": "no",
        "ኗ": "naa",
        "ኘ": "nye",
        "ኙ": "nyu",
        "ኚ": "nyi",
        "ኛ": "nya",
        "ኜ": "nyee",
        "ኝ": "ny",
        "ኞ": "nyo",
        "ኟ": "nyaa",
        "አ": "e",
        "ኡ": "u",
        "ኢ": "i",
        "ኣ": "a",
        "ኤ": "ee",
        "እ": "ə",
        "ኦ": "o",
        "ኧ": "aa",
        "ከ": "ke",
        "ኩ": "ku",
        "ኪ": "ki",
        "ካ": "ka",
        "ኬ": "kee",
        "ክ": "k",
        "ኮ": "ko",
        "ኯ": "koe",
        "ኸ": "xe",
        "ኹ": "xu",
        "ኺ": "xi",
        "ኻ": "xa",
        "ኼ": "xee",
        "ኽ": "x",
        "ኾ": "xo",
        "ወ": "we",
        "ዉ": "wu",
        "ዊ": "wi",
        "ዋ": "wa",
        "ዌ": "wee",
        "ው": "w",
        "ዎ": "wo",
        "ዐ": "e",
        "ዑ": "u",
        "ዒ": "i",
        "ዓ": "a",
        "ዔ": "ee",
        "ዕ": "ə",
        "ዖ": "o",
        "ዘ": "ze",
        "ዙ": "zu",
        "ዚ": "zi",
        "ዛ": "za",
        "ዜ": "zee",
        "ዝ": "z",
        "ዞ": "zo",
        "ዟ": "zaa",
        "ዠ": "zhe",
        "ዡ": "zhu",
        "ዢ": "zhi",
        "ዣ": "zha",
        "ዤ": "zhee",
        "ዥ": "zh",
        "ዦ": "zho",
        "ዧ": "zhaa",
        "የ": "ye",
        "ዩ": "yu",
        "ዪ": "yi",
        "ያ": "ya",
        "ዬ": "yee",
        "ይ": "y",
        "ዮ": "yo",
        "ደ": "de",
        "ዱ": "du",
        "ዲ": "di",
        "ዳ": "da",
        "ዴ": "dee",
        "ድ": "d",
        "ዶ": "do",
        "ዷ": "daa",
        "ጀ": "je",
        "ጁ": "ju",
        "ጂ": "ji",
        "ጃ": "ja",
        "ጄ": "jee",
        "ጅ": "j",
        "ጆ": "jo",
        "ጇ": "jaa",
        "ገ": "ge",
        "ጉ": "gu",
        "ጊ": "gi",
        "ጋ": "ga",
        "ጌ": "gee",
        "ግ": "g",
        "ጎ": "go",
        "ጏ": "gaa",
        "ጠ": "the",
        "ጡ": "thu",
        "ጢ": "thi",
        "ጣ": "tha",
        "ጤ": "thee",
        "ጥ": "th",
        "ጦ": "tho",
        "ጧ": "thaa",
        "ጨ": "che",
        "ጩ": "chu",
        "ጪ": "chi",
        "ጫ": "cha",
        "ጬ": "chee",
        "ጭ": "ch",
        "ጮ": "cho",
        "ጯ": "chaa",
        "ጰ": "phe",
        "ጱ": "phu",
        "ጲ": "phi",
        "ጳ": "pha",
        "ጴ": "phee",
        "ጵ": "ph",
        "ጶ": "pho",
        "ጷ": "phaa",
        "ጸ": "tse",
        "ጹ": "tsu",
        "ጺ": "tsi",
        "ጻ": "tsa",
        "ጼ": "tsee",
        "ጽ": "ts",
        "ጾ": "tso",
        "ጿ": "tsaa",
        "ፀ": "tze",
        "ፁ": "tzu",
        "ፂ": "tzi",
        "ፃ": "tza",
        "ፄ": "tzee",
        "ፅ": "tz",
        "ፆ": "tzo",
        "ፈ": "fe",
        "ፉ": "fu",
        "ፊ": "fi",
        "ፋ": "fa",
        "ፌ": "fee",
        "ፍ": "f",
        "ፎ": "fo",
        "ፏ": "faa",
        "ፐ": "pe",
        "ፑ": "pu",
        "ፒ": "pi",
        "ፓ": "pa",
        "ፔ": "pee",
        "ፕ": "p",
        "ፖ": "po",
        "ፗ": "paa"
    };

    //convert to ameharic to english 
    amharicToLatinTransliterate(input: string): string {
        let result = '';

        console.log("input " + input)
        for (const char of input) {
            const mapped = this.amharicToEnglish[char];

            console.log("maped " + mapped)
            if (mapped === undefined) {
                result += " ";
            }
            else {
                result += mapped;  // or keep the original char if you prefer
            }
        }
        return result;
    }

    isAmharicString(text: string): boolean {
        for (const char of text) {
            const code = char.charCodeAt(0);
            const isAmharicChar =
                (code >= 0x1200 && code <= 0x137F) || // Ethiopic
                (code >= 0x1380 && code <= 0x139F) || // Ethiopic Supplement
                (code >= 0x2D80 && code <= 0x2DDF);   // Ethiopic Extended

            if (!isAmharicChar) return false;
        }
        return true;
    }

    isEnglish(text: string): boolean {
        for (const character of text) {
            const code = character.charCodeAt(0);
            if (
                (code >= 0x0041 && code <= 0x005A) || // A-Z
                (code >= 0x0061 && code <= 0x007A)    // a-z
            ) {
                return true;
            }
        }
        return false;
    }
    getCountryKeyByValue(value: string): string | undefined {
        for (const key in this.countryMap) {
            if (this.countryMap[key] === value) {
                return key;
            }
        }
        return undefined; // return undefined if not found
    }
    countryExistsByValue(value: string): boolean {
        for (const key in this.countryMap) {
            if (this.countryMap[key] === value) {
                return true;
            }
        }
        return false;
    }

  

    getShortDescription(description: string): string {
        if (description.length > this.getMaxDescriptionLength(description)) {
          return description.slice(0, this.getMaxDescriptionLength(description)).trim() + '';
        }
        return description;
      }
    
      isAmharic(char: string): boolean {
        if (!char) return false;
        const code = char.charCodeAt(0);
        return (
          (code >= 0x1200 && code <= 0x137F) || 
          (code >= 0x1380 && code <= 0x139F) || 
          (code >= 0x2D80 && code <= 0x2DDF)
        );
      }
      
      getMaxDescriptionLength(description: string): number {
        return this.isAmharic(description[0]) ? 90 : 100;
      }


      public getTitleClass(header: string): string {
   
        return  this.isAmharic(header) ? 'A-title' : 'E-title';
      }
}
